-- MySQL Script generated by MySQL Workbench
-- Sun Jun  7 20:40:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema tpsofbd
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `tpsofbd` DEFAULT CHARACTER SET utf8 ;
USE `tpsofbd` ;

-- -----------------------------------------------------
-- Table `tpsofbd`.`user_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`user_manager` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`user_manager` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(45) NULL COMMENT '用户名,必填,唯一',
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL COMMENT '邮箱为选填项',
  `is_admin` TINYINT NULL COMMENT '是否是管理员用户',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpsofbd`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`category` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `level1_name` VARCHAR(45) NULL COMMENT '资源类目1名称',
  `level2_name` VARCHAR(45) NULL COMMENT '资源类目2名称',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpsofbd`.`markdown_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`markdown_file` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`markdown_file` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `markdown_file_url` VARCHAR(45) NULL,
  `click_count` BIGINT UNSIGNED NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpsofbd`.`sourcecode_fille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`sourcecode_fille` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`sourcecode_fille` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `sourcecode_fill_url` VARCHAR(45) NULL,
  `download_count` BIGINT UNSIGNED NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpsofbd`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`resource` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`resource` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '资源名称',
  `image_url` VARCHAR(45) NULL COMMENT '资源展示背景图url',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `category_id` BIGINT UNSIGNED NOT NULL,
  `markdown_file_id` BIGINT UNSIGNED NOT NULL,
  `sourcecode_fille_id` BIGINT UNSIGNED NOT NULL,
  `star_count` BIGINT UNSIGNED NULL COMMENT '收藏数',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpsofbd`.`sourcecode_fille_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`sourcecode_fille_user_relation` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`sourcecode_fille_user_relation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `sourcecode_fille_id` BIGINT UNSIGNED NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpsofbd`.`markdown_fille_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`markdown_fille_user_relation` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`markdown_fille_user_relation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `markdown_file_id` BIGINT UNSIGNED NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tpsofbd`.`resource_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tpsofbd`.`resource_user_relation` ;

CREATE TABLE IF NOT EXISTS `tpsofbd`.`resource_user_relation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `resource_id` BIGINT UNSIGNED NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


